name: "Automated & Manual Workflow"

on:
  push:
  workflow_dispatch:  # Allows manual trigger

jobs:
  automated_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Automated
        run: echo "Running Step 1"

      - name: Step 2 - Automated
        run: echo "Running Step 2"

      - name: Step 3 - Automated
        run: echo "Running Step 3"

  manual_step:
    runs-on: ubuntu-latest
    needs: automated_steps  # Waits for previous job
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: myteam
          minimum-approvals: 1

      - name: Step 4 - Manual Trigger Needed
        run: echo "Waiting for manual approval..."
